title: "Creative Docs"
description: "Documentation about Gimkit Creative"
theme: just-the-docs

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

just_the_docs:
  search_enabled: true
  nav_sort: case_insensitive
